import { Check, MapPin, Star, Truck } from 'lucide-react';
export type Food = { id:string; name:string; price:number; seller:string; occupation:string; image:string; rating:number; distance:string; dietary:string; allergen:string; quantity:number; delivery:boolean; };
export const foods:Food[]=[
{id:'1',name:'Homemade Paneer Thali',price:150,seller:'Priya Sharma',occupation:'Verified Student',image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',rating:4.8,distance:'1.2 km',dietary:'Vegetarian',allergen:'Dairy',quantity:6,delivery:true},
{id:'2',name:'Sunday Veg Biryani',price:220,seller:'Aarav Mehta',occupation:'Verified Employee',image:'https://images.unsplash.com/photo-1563379091339-03246963d51a?auto=format&fit=crop&w=900&q=80',rating:4.9,distance:'2.4 km',dietary:'Vegetarian',allergen:'Dairy',quantity:4,delivery:true},
{id:'3',name:'Aai’s Dal Khichdi',price:120,seller:'Meera Kulkarni',occupation:'Verified Community Member',image:'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=80',rating:4.7,distance:'0.8 km',dietary:'Jain',allergen:'None',quantity:8,delivery:false},
{id:'4',name:'Soft Aloo Paratha',price:90,seller:'Neha Verma',occupation:'Verified Homemaker',image:'https://images.unsplash.com/photo-1617692855027-33b14f061079?auto=format&fit=crop&w=900&q=80',rating:4.8,distance:'1.7 km',dietary:'Vegetarian',allergen:'Gluten, Dairy',quantity:5,delivery:true},
{id:'5',name:'Fresh Idli & Sambar',price:110,seller:'Rohan Iyer',occupation:'Verified Student',image:'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=80',rating:4.6,distance:'3.1 km',dietary:'Vegan',allergen:'None',quantity:10,delivery:false},
{id:'6',name:'Amma’s Modak Box',price:180,seller:'Kavita Patil',occupation:'Verified Home Seller',image:'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=900&q=80',rating:5,rating:5,distance:'1.4 km',dietary:'Vegetarian',allergen:'Tree nuts',quantity:3,delivery:true}
];
export function VerificationBadges(){return <div className="flex flex-wrap gap-1.5"><span className="pill"><Check size={12}/> Identity verified</span><span className="pill">✓ Food safety</span></div>}
export function FoodCard({food}:{food:Food}){return <article className="card group overflow-hidden"><a href={`/food/${food.id}`}><div className="relative h-52 overflow-hidden"><img src={food.image} alt={food.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 rounded-full bg-white/95 px-3 py-1 text-xs font-bold text-[#1f6b4f]">{food.dietary}</span></div></a><div className="p-5"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold text-lg text-[#17352b]">{food.name}</h3><p className="mt-1 text-sm text-gray-500">{food.seller} · {food.occupation}</p></div><b className="whitespace-nowrap text-lg text-[#1f6b4f]">₹{food.price}</b></div><div className="mt-3"><VerificationBadges/></div><div className="mt-4 flex flex-wrap gap-3 text-xs text-gray-500"><span className="flex items-center gap-1"><Star size={14} fill="#f4a261" className="text-[#f4a261]"/> {food.rating}</span><span className="flex items-center gap-1"><MapPin size={14}/> {food.distance}</span><span className="flex items-center gap-1"><Truck size={14}/> {food.delivery?'Pickup + delivery':'Pickup only'}</span></div><p className="mt-3 text-xs text-gray-500">Contains: <b className="text-gray-700">{food.allergen}</b> · Available {food.quantity} / 10</p><a href={`/food/${food.id}`} className="btn-primary mt-4 w-full">View details</a></div></article>}
